/*******************************************************************************
 * wallaroo - A library for configurable creation and wiring of C++ classes.
 * Copyright (C) 2012 Daniele Pallastrelli
 *
 * This file is part of wallaroo.
 * For more information, see http://wallaroo.googlecode.com/
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#include <boost/test/unit_test.hpp>

#include "wallaroo/registered.h"
#include "wallaroo/catalog.h"

using namespace wallaroo;
using namespace cxx0x;

// some classes:

class A1 : public Device
{
public:
    int F() { return 5; }
};

WALLAROO_REGISTER( A1 );
//static const Registration< A1 > r( "A1" );

class B1: public Device
{
public:
    B1( int _x, const std::string& _y ) : x( _x ), y( _y ) {}
    int GetX() const { return x; }
    const std::string& GetY() const { return y; }
    ~B1() {}
private:
    const int x;
    const std::string y;
};

WALLAROO_REGISTER( B1, int, std::string );
//static const Registration< B1, int, std::string > r2( "B1" );

class C1: public Device
{
public:
    C1( double _x ) : x( _x ) {}
    double GetX() const { return x; }
private:
    double x;
};

WALLAROO_REGISTER( C1, double );
//static const Registration< C1, double > r3( "C1" );

// tests

BOOST_AUTO_TEST_SUITE( Creation )

BOOST_AUTO_TEST_CASE( creationOk )
{
    Catalog catalog;
    BOOST_REQUIRE_NO_THROW( catalog.Create( "a", "A1" ) );
    BOOST_REQUIRE_NO_THROW( catalog[ "a" ] );
}

BOOST_AUTO_TEST_CASE( creationUnexistentObj )
{
    Catalog catalog;
    BOOST_CHECK_THROW( catalog.Create( "a", "Unknown" ), ElementNotFound );
}

BOOST_AUTO_TEST_CASE( duplicatedElement )
{
    Catalog catalog;
    BOOST_REQUIRE_NO_THROW( catalog.Create( "a", "A1" ) );
    BOOST_CHECK_THROW( catalog.Create( "a", "B1", 10, std::string( "hello" ) ), DuplicatedElement );
}

BOOST_AUTO_TEST_CASE( retrieveOk )
{
    Catalog catalog;
    shared_ptr< A1 > a1;
    shared_ptr< A1 > a2;
    BOOST_REQUIRE_NO_THROW( a1 = catalog.Create( "a", "A1" ) );
    BOOST_REQUIRE_NO_THROW( a2 = catalog[ "a" ] );
    BOOST_CHECK( a1 -> F() == 5 );
    BOOST_CHECK( a1 == a2 );
}

BOOST_AUTO_TEST_CASE( retrieveKo )
{
    Catalog catalog;
    BOOST_CHECK_THROW( catalog[ "b" ], ElementNotFound );
}

BOOST_AUTO_TEST_CASE( multipleParametersOk )
{
    Catalog catalog;

    BOOST_REQUIRE_NO_THROW( catalog.Create( "b", "B1", 10, std::string( "hello" ) ) );
    BOOST_REQUIRE_NO_THROW( catalog[ "b" ] );
    shared_ptr< B1 > b = catalog[ "b" ];
    BOOST_CHECK( b -> GetX() == 10 );
    BOOST_CHECK( b -> GetY() == "hello" );

    BOOST_REQUIRE_NO_THROW( catalog.Create( "c", "C1", (double)69.0 ) );
    BOOST_REQUIRE_NO_THROW( catalog[ "c" ] );
    shared_ptr< C1 > c = catalog[ "c" ];
    BOOST_CHECK( c -> GetX() == (double)69.0 );
}

#if 0 // fails because we use const char* instead of std::string
BOOST_AUTO_TEST_CASE( stringCtor )
{
    Catalog catalog;
    BOOST_REQUIRE_NO_THROW( catalog.Create( "b", "B1", 10, "hello" ) );
    BOOST_REQUIRE_NO_THROW( catalog[ "b" ] );
}
#endif

BOOST_AUTO_TEST_SUITE_END()