/*******************************************************************************
 * wallaroo - A library for configurable creation and wiring of C++ classes.
 * Copyright (C) 2012 Daniele Pallastrelli
 *
 * This file is part of wallaroo.
 * For more information, see http://wallaroo.googlecode.com/
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#include <cmath>
#include "circle.h"

WALLAROO_REGISTER( Circle );

Circle::Circle() :
    radius( "radius", RegistrationToken() ),
    xCenter( 0 ),
    yCenter( 0 )
{
}

Box Circle::BoundingBox() const
{
    return Box( xCenter-radius, yCenter-radius, xCenter+radius, yCenter+radius );
}

void Circle::Draw( cxx0x::shared_ptr< Canvas > canvas ) const
{
    using namespace std;

    static const unsigned int increment = 5;

    for ( unsigned int angle = 0; angle < 360; angle += increment )
    {
        const double rad = static_cast< double >( angle * 6.28 / 360.0 );
        unsigned int x = static_cast< unsigned int >( floor( 0.5 + xCenter + radius * sin( rad ) ) );
        unsigned int y = static_cast< unsigned int >( floor( 0.5 + yCenter + radius * cos( rad ) ) );
        canvas -> Point( x, y );
    }
}

void Circle::MoveX( int delta )
{
    xCenter += delta;
}

void Circle::MoveY( int delta )
{
    yCenter += delta;
}
