/*******************************************************************************
 * wallaroo - A library for configurable creation and wiring of C++ classes.
 * Copyright (C) 2012 Daniele Pallastrelli
 *
 * This file is part of wallaroo.
 * For more information, see http://wallaroo.googlecode.com/
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef WALLAROO_DEVICE_H_
#define WALLAROO_DEVICE_H_

#include <string>
#include "exceptions.h"
#include "cxx0x.h"
#include "connector.h"

namespace wallaroo
{

// forward declaration:
class Plugin;

class RegToken
{
public:
    Device* GetDevice() const { return device; }
private:
    friend class Device;
    RegToken( Device* d ) : device( d ) {}
    Device* device;
};

/**
 * This class represents a "device" that owns connectors.
 * You can plug its connectors to other devices using the method Device::Wire.
 */
class Device
{
public:
    // we need to make Device virtual, to use dynamic_cast
    virtual ~Device() {}

    /** Plug the connector @c connector of this device into the Device @c device.
     * @throw ElementNotFound if @c connector does not exist in this device.
     */
    void Wire( const std::string& connector, const cxx0x::shared_ptr< Device >& device )
    {
        Connectors::iterator i = connectors.find( connector );
        if ( i == connectors.end() ) 
            throw ElementNotFound( connector );
        ( i -> second ) -> PlugInto( device );
    }


   /** Check the multiplicity of its plugs.
    * @return true if the check pass
    */
    bool MultiplicitiesOk() const
    {
        for ( 
            Connectors::const_iterator i = connectors.begin();
            i != connectors.end();
            ++i
        )
            if ( ! i -> second -> WiringOk() )
                return false;
        return true;
    }

protected:
    RegToken RegistrationToken()
    { 
        return RegToken( this );
    }
private:
    // this method should only be invoked by Class
    // to add the reference counter for the shared library.
    template < class T1, class T2 > friend class Class;
    void Source( const cxx0x::shared_ptr< Plugin >& p )
    {
        plugin = p;
    }

    // this method should only be invoked by the connectors of this device
    // to register itself into the connectors table.
    template < class T, class P, template < typename E, typename Allocator = std::allocator< E > > class Container > friend class Plug;
    void Register( const std::string& id, Connector* plug )
    {
        connectors[ id ] = plug;
    }

    typedef cxx0x::unordered_map< std::string, Connector* > Connectors;
    Connectors connectors;
    cxx0x::shared_ptr< Plugin > plugin; // optional shared ptr to plugin, to release the shared library when is no more used
};

} // namespace

#endif
