/*******************************************************************************
 * wallaroo - A library for configurable creation and wiring of C++ classes.
 * Copyright (C) 2012 Daniele Pallastrelli
 *
 * This file is part of wallaroo.
 * For more information, see http://wallaroo.googlecode.com/
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef WALLAROO_DYNAMIC_LIB_H_
#define WALLAROO_DYNAMIC_LIB_H_

#include <vector>
#include "detail/dyn_class_descriptor.h"
#include "detail/dyn_class_descriptor_impl.h"
#include "detail/platform_specific_lib_macros.h"

/** This macro must be used in the shared libraries
 * to register a class. When a class is registered, you can create an instance
 * using wallaroo::Catalog::Create().
 * Please note you can put multiple registration clauses, if you have multiple classes
 * defined in the same shared library.
 * @param C The class name
 * @hideinitializer
 */
#define WALLAROO_DYNLIB_REGISTER( C ) \
    static wallaroo::detail::DynRegistration< C > C##p( #C );

// This function is exported by the shared library when you include this header
// file. It provides a container of descriptors of the classes exported by
// the library.
WALLAROO_DLL_PREFIX
std::vector< wallaroo::detail::Descriptor >* GetClasses()
{
    return &wallaroo::detail::Descriptor::DB();
}

#endif // WALLAROO_DYNAMIC_LIB_H_

