/*******************************************************************************
 * wallaroo - A library for configurable creation and wiring of C++ classes.
 * Copyright (C) 2012 Daniele Pallastrelli
 *
 * This file is part of wallaroo.
 * For more information, see http://wallaroo.googlecode.com/
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

#ifndef WALLAROO_EXCEPTIONS_H_
#define WALLAROO_EXCEPTIONS_H_

#include <stdexcept>

namespace wallaroo
{

/** Base class for all Wallaroo errors. Derives from
* @c std::runtime_error. Call member function @c what to get human
* readable message associated with the error.
*/
class WallarooError : public std::runtime_error
{
public:
    /** Instantiate a WallarooError instance with the given message.
    * @param what The message to associate with this error.
    */
    WallarooError( const std::string &what ) : 
        std::runtime_error( what ) 
    {
    }

    ~WallarooError() throw()
    {
    }
};


/** Error indicating that specified Device does not exist anymore because it has
* been deleted. Derives from WallarooError.
*/
class DeletedDeviceError : public WallarooError
{
public:
    /// Instantiate a DeletedDeviceError
    DeletedDeviceError() :
        WallarooError( "The device has been deleted" )
    {
    }

    ~DeletedDeviceError() throw()
    {
    }
};


/** Error indicating that a @c use expression has been used outside a 
*   wallaroo_within section. Derives from WallarooError.
*/
class CatalogNotSpecified : public WallarooError
{
public:
    /// Instantiate a CatalogNotSpecified
    CatalogNotSpecified() :
        WallarooError( "The catalog has not been specified. You must use a wallaroo_within section." )
    {
    }

    ~CatalogNotSpecified() throw()
    {
    }
};


/** Error indicating that a cast has been performed with the wrong types.
*   Derives from WallarooError.
*/
class WrongType : public WallarooError
{
public:
    /// Instantiate a WrongType
    WrongType() :
        WallarooError( "The type is wrong for the cast." )
    {
    }

    ~WrongType() throw()
    {
    }
};


/** Error indicating that an item was not found in the catalog or in the class.
*   Derives from WallarooError.
*/
class ElementNotFound : public WallarooError
{
public:
    /// Instantiate a ElementNotFound
    ElementNotFound( const std::string& _element ) :
        WallarooError( _element + " not found in the container" ),
        element( _element )
    {
    }
    ~ElementNotFound() throw()
    {
    }
    const std::string& Element() const
    {
        return element;
    }
private:
    const std::string element;
};


/** Error indicating that an item was already inserted in the catalog or in the class.
*   Derives from WallarooError.
*/
class DuplicatedElement : public WallarooError
{
public:
    /// Instantiate a DuplicatedElement
    DuplicatedElement( const std::string& _element ) :
        WallarooError( _element  + " already in the container" ),
        element( _element )
    {
    }
    ~DuplicatedElement() throw()
    {
    }
    const std::string& Element() const
    {
        return element;
    }
private:
    const std::string element;
};


/** Error indicating that the file does not exist or contains a semantic error.
*   Derives from WallarooError.
*/
class WrongFile : public WallarooError
{
public:
    /// Instantiate a WrongFile
    explicit WrongFile( const std::string& msg ) :
        WallarooError( msg )
    {
    }

    ~WrongFile() throw()
    {
    }
};

/** Error indicating that a plug has not been wired correctly.
*   Derives from WallarooError.
*/
class WiringError : public WallarooError
{
public:
    /// Instantiate a WiringError
    WiringError( const std::string& _element ) :
        WallarooError( _element  + " wiring error" ),
        element( _element )
    {
    }
    ~WiringError() throw()
    {
    }
    const std::string& Element() const
    {
        return element;
    }
private:
    const std::string element;
};

} // namespace

#endif
